---
apiVersion: v1
kind: Pod
metadata:
  name: pgstac-client
  namespace: db
  labels:
    app: pgstac-client
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"    
spec: 
  containers:
    - name: pgstac-client
      image: ghcr.io/stac-utils/stac-fastapi:2.4.5-pgstac
      imagePullPolicy: Always
      stdin: true
      tty: true
      command: ["/bin/sh"]
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-admin-creds
              key: password
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-admin-creds
              key: username
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-admin-creds
              key: hostname
